console.log("this is a ts file");
console.log("this is a ts file2");
var addFun = function (a, b) { return a + b; };
var addFunReturn = addFun(1, 2);
console.log('addFunReturn', addFunReturn);
var subFun = function (a, b) { return a - b; };
var subFunReturn = subFun(10, 5);
console.log('subFunReturn', subFunReturn);
var multiFun = function (a, b) { return a * b; };
var multiFunReturn = multiFun(10, 5);
console.log('multiFunReturn', multiFunReturn);
var divFun = function (a, b) { return a / b; };
var divFunReturn = divFun(10, 5);
console.log('divFunReturn', divFunReturn);
